#include "unity.h"

void setUp(void) {} /* Is run before every test, put unit init calls here. */
void tearDown(void) {} /* Is run after every test, put unit clean-up calls here. */

#include "my_enum.h"

void test_enum(void) {
    TEST_ASSERT_EQUAL(0, MY_NAMESPACE_ONE);
    TEST_ASSERT_EQUAL(1, MY_NAMESPACE_TWO);
    TEST_ASSERT_EQUAL(2, MY_NAMESPACE_THREE);
    TEST_ASSERT_EQUAL(3, MY_NAMESPACE_FOUR);
}

void test_enum_flags(void) {
    TEST_ASSERT_EQUAL(1 << 0, MY_NAMESPACE_ONE_FLAG);
    TEST_ASSERT_EQUAL(1 << 1, MY_NAMESPACE_TWO_FLAG);
    TEST_ASSERT_EQUAL(1 << 2, MY_NAMESPACE_THREE_FLAG);
    TEST_ASSERT_EQUAL(1 << 3, MY_NAMESPACE_FOUR_FLAG);
}

void test_enum_strings(void) {
    TEST_ASSERT_EQUAL_STRING("MY_NAMESPACE_ONE", MY_NAMESPACE_STRINGS[MY_NAMESPACE_ONE]);
    TEST_ASSERT_EQUAL_STRING("MY_NAMESPACE_TWO", MY_NAMESPACE_STRINGS[MY_NAMESPACE_TWO]);
    TEST_ASSERT_EQUAL_STRING("MY_NAMESPACE_THREE", MY_NAMESPACE_STRINGS[MY_NAMESPACE_THREE]);
    TEST_ASSERT_EQUAL_STRING("MY_NAMESPACE_FOUR", MY_NAMESPACE_STRINGS[MY_NAMESPACE_FOUR]);
}

void test_offset_enum(void) {
    TEST_ASSERT_EQUAL(0, ZERO);
    TEST_ASSERT_EQUAL(1, ONE);
    TEST_ASSERT_EQUAL(20, OFFSET_TWENTY);
    TEST_ASSERT_EQUAL(21, OFFSET_TWENTY1);
    TEST_ASSERT_EQUAL(22, OFFSET_TWENTY2);
    TEST_ASSERT_EQUAL(23, OFFSET_TWENTY3);
    TEST_ASSERT_EQUAL(40, OFFSET_FORTY);
    TEST_ASSERT_EQUAL(41, OFFSET_FORTY1);
    TEST_ASSERT_EQUAL(42, OFFSET_FORTY2);
    TEST_ASSERT_EQUAL(43, OFFSET_FORTY3);
}

void test_offset_enum_strings(void) {
    TEST_ASSERT_EQUAL_STRING("OFFSET_TWENTY", OFFSET1_STRINGS[0]);
    TEST_ASSERT_EQUAL_STRING("OFFSET_TWENTY1", OFFSET1_STRINGS[1]);
    TEST_ASSERT_EQUAL_STRING("OFFSET_TWENTY2", OFFSET1_STRINGS[2]);
    TEST_ASSERT_EQUAL_STRING("OFFSET_TWENTY3", OFFSET1_STRINGS[3]);

    TEST_ASSERT_EQUAL_STRING("OFFSET_FORTY", OFFSET2_STRINGS[0]);
    TEST_ASSERT_EQUAL_STRING("OFFSET_FORTY1", OFFSET2_STRINGS[1]);
    TEST_ASSERT_EQUAL_STRING("OFFSET_FORTY2", OFFSET2_STRINGS[2]);
    TEST_ASSERT_EQUAL_STRING("OFFSET_FORTY3", OFFSET2_STRINGS[3]);
}

void test_IC_MAKE_STRING_GETTER(void) {
    TEST_ASSERT_EQUAL_STRING("MY_NAMESPACE_ONE", MY_NAMESPACE_STRING(MY_NAMESPACE_ONE));
    TEST_ASSERT_EQUAL_STRING("MY_NAMESPACE_TWO", MY_NAMESPACE_STRING(MY_NAMESPACE_TWO));
    TEST_ASSERT_EQUAL_STRING("MY_NAMESPACE_THREE", MY_NAMESPACE_STRING(MY_NAMESPACE_THREE));
    TEST_ASSERT_EQUAL_STRING("MY_NAMESPACE_FOUR", MY_NAMESPACE_STRING(MY_NAMESPACE_FOUR));

    TEST_ASSERT_EQUAL_STRING("OFFSET_TWENTY", OFFSET1_STRING(OFFSET_TWENTY));
    TEST_ASSERT_EQUAL_STRING("OFFSET_TWENTY1", OFFSET1_STRING(OFFSET_TWENTY1));
    TEST_ASSERT_EQUAL_STRING("OFFSET_TWENTY2", OFFSET1_STRING(OFFSET_TWENTY2));
    TEST_ASSERT_EQUAL_STRING("OFFSET_TWENTY3", OFFSET1_STRING(OFFSET_TWENTY3));
    TEST_ASSERT_EQUAL_STRING("Enum out of bounds", OFFSET1_STRING(24));
    TEST_ASSERT_EQUAL_STRING("Enum out of bounds", OFFSET1_STRING(-1));

    TEST_ASSERT_EQUAL_STRING("OFFSET_FORTY", OFFSET2_STRING(OFFSET_FORTY));
    TEST_ASSERT_EQUAL_STRING("OFFSET_FORTY1", OFFSET2_STRING(OFFSET_FORTY1));
    TEST_ASSERT_EQUAL_STRING("OFFSET_FORTY2", OFFSET2_STRING(OFFSET_FORTY2));
    TEST_ASSERT_EQUAL_STRING("OFFSET_FORTY3", OFFSET2_STRING(OFFSET_FORTY3));
    TEST_ASSERT_EQUAL_STRING("Enum out of bounds", OFFSET2_STRING(44));
    TEST_ASSERT_EQUAL_STRING("Enum out of bounds", OFFSET2_STRING(-1));

    TEST_ASSERT_EQUAL_STRING("ERR_128", ERR_STRING(ERR_128));
    TEST_ASSERT_EQUAL_STRING("ERR_127", ERR_STRING(ERR_127));
    TEST_ASSERT_EQUAL_STRING("Enum out of bounds", ERR_STRING(-129));
    TEST_ASSERT_EQUAL_STRING("Enum out of bounds", ERR_STRING(-126));
}

void test_negative_enums(void) {
    TEST_ASSERT_EQUAL(-128, ERR_128);
    TEST_ASSERT_EQUAL(-127, ERR_127);

    TEST_ASSERT_EQUAL_STRING("ERR_128", ERR_STRINGS[0]);
    TEST_ASSERT_EQUAL_STRING("ERR_127", ERR_STRINGS[1]);
}

void test_get_flag_string(void) {
    const unsigned ONE_TWO_FOUR = 0b00001011U;
    char const * const ANSWERS[] = {
        "MY_NAMESPACE_ONE",
        "MY_NAMESPACE_TWO",
        "MY_NAMESPACE_FOUR",
    };

    int answer_idx = 0;
    for (int i = 0; i <= MY_NAMESPACE_FOUR; ++i) {
        if ((1U << i) & ONE_TWO_FOUR) {
            TEST_ASSERT_EQUAL_STRING(ANSWERS[answer_idx], MY_NAMESPACE_STRING(i));
            answer_idx += 1;
        }
    }

    TEST_ASSERT_EQUAL(sizeof(ANSWERS) / sizeof(ANSWERS[0]), answer_idx);
}

int main(void) {
    UNITY_BEGIN();

    RUN_TEST(test_enum);
    RUN_TEST(test_enum_flags);
    RUN_TEST(test_enum_strings);
    RUN_TEST(test_offset_enum);
    RUN_TEST(test_offset_enum_strings);
    RUN_TEST(test_IC_MAKE_STRING_GETTER);
    RUN_TEST(test_negative_enums);
    RUN_TEST(test_get_flag_string);

    return UNITY_END();
}